remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Diffusion-HIC
description: An end-to-end diffusion generative model for heavy-ion collisions
author: Jing-An
markdown: kramdown
kramdown:
  math_engine: mathjax
